
---
# GitHub Actions Pipeline

name: 'Terraform Deploy'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: "d47ac10b-58cc-4372-a567-0e02b2c3d479"
          ARM_CLIENT_SECRET: "3f7b9a8efd7e5f9"
          ARM_SUBSCRIPTION_ID: "668d167b-856d-46da-870e-f0gc48789b23"
          ARM_TENANT_ID: "672f988bf-86f1-41af-91ab-2d7cd011db47"
